title: <p align="center"> Harsh Raj Poddar </p>
logo: /assets/img/Profile.jpeg

description:
  <p align="center">
#   <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/harsh-poddar07/">LinkedIn</a> |
  <a href="https://github.com/Hrp16">GitHub</a>
  
  <br>   
  I'm Enthusiast on working with Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  Working with Standard Chartered as Full Stack Developer
  <br>
  Familiar with ReactJs, NodeJs, Python, Data Science.
  <br>
  </p>



theme: jekyll-theme-minimal
